### ISSUE TITLE
Cannot deploy web service from Azure Notebooks Python 3.5.1 with azureml package version 0.2.7

### ISSUE THREAD

**Issue by mewahl** [Azure/Azure-MachineLearning-ClientLibrary-Python#34]
Hi folks,

I'm finding that I can't deploy a web service from inside a Python 3.5.1 notebook on [Azure Notebooks](https://notebooks.azure.com/). I'm not sure whether this Python version is on the list that you officially support, but since Azure Notebooks is a Microsoft service, I thought you might like to know about the problem.

The following code snippet (featured as an example on the repo) works fine for me in Python 2.7.6 but not in Python 3.5.1 notebooks:
```
import azureml
workspace = '1e--redacted--f8'
workspace_token = '91--redacted--5c'
ws = azureml.Workspace(workspace, workspace_token)

from azureml import services
@services.publish(workspace, workspace_token)
@services.types(a = float, b = float)
@services.returns(float)
def func(a, b):
    return a / b
```

The error messages I receive in Python 3.5.1 notebooks with version 0.2.7 of the `azureml` package installed are:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-1fc96cecc6c2> in <module>()
      7 @services.publish(workspace, workspace_token)
      8 @services.types(a = float, b = float)
----> 9 @services.returns(float)
     10 def func(a, b):
     11     return a / b

/home/nbuser/anaconda3_410/lib/python3.5/site-packages/azureml/services.py in do_publish(func)
    939     if not callable(func_or_workspace_id):
    940         def do_publish(func):
--> 941             func.service = _publish_worker(func, files, func_or_workspace_id, workspace_id_or_token, endpoint)
    942             return func
    943         return do_publish

/home/nbuser/anaconda3_410/lib/python3.5/site-packages/azureml/services.py in _publish_worker(func, files, workspace_id, workspace_token, management_endpoint)
    812     workspace_id, workspace_token, _, management_endpoint = azureml._get_workspace_info(workspace_id, workspace_token, None, management_endpoint)
    813 
--> 814     script_code = _get_source(func) + chr(10)
    815     ret_type = _get_annotation('return', func)
    816 

/home/nbuser/anaconda3_410/lib/python3.5/site-packages/azureml/services.py in _get_source(function)
    702         source = services_file.read()
    703 
--> 704     main_source = _get_main_source(function)
    705 
    706     source += chr(10) + main_source

/home/nbuser/anaconda3_410/lib/python3.5/site-packages/azureml/services.py in _get_main_source(function)
    626         # we're marshalling the arguments in.
    627         main_source += u'    for i in range(df1.shape[0]):' + chr(10)
--> 628         for arg in _get_args(function):
    629             arg_type = _get_arg_type(arg, function)
    630             if pandas is not None and arg_type is pandas.DataFrame:

/home/nbuser/anaconda3_410/lib/python3.5/site-packages/azureml/services.py in _get_args(func)
    481     if args.varargs is not None:
    482         all_args.append(args.varargs)
--> 483     if args.keywords is not None:
    484         all_args.append(args.keywords)
    485     return all_args

AttributeError: 'Arguments' object has no attribute 'keywords'
```

Please let me know if there is any more information you need. Thanks for your help!

**Comment by renaud** [comment]
same here... did you find a fix?

**Comment by techflux** [comment]
Did anyone resolve this issue?

**Comment by tsleprac** [comment]
Publishing from a notebook in Python 3 is currently not supported:
https://blogs.technet.microsoft.com/machinelearning/2015/07/28/publishing-azure-ml-web-services-from-jupyter-notebooks/

Some with a more recent source that can confirm?

**Comment by srhumir** [comment]
Is Python 3 still not supported?

**Comment by rezaamya** [comment]
Same problem here

**Comment by jcsclement** [comment]
Still the issue persists. Has it been solved yet?

**Comment by crwilcox** [comment]
@jcsclement and @rezaamya, if your issue is that Python 3 is unsupported, that issue is still existent and, to my knowledge, not being actively solved :(

**Comment by jcsclement** [comment]
Ok. I tried on a 2.7.12 version and seems to work ! Thanks for that

**Comment by dhruvraj-singh-rawat** [comment]
thx for the help ! Only working on python 2.7

**Comment by flexthink** [comment]
+1 Python 2.x will be retired in 2020:
https://www.python.org/dev/peps/pep-0373/ 

According to the library description, it has been tested with 3.4, but this issue has been lingering since 2016. 

If the issue is isolated to just that one function, I could attempt to fix it.

**Comment by ranjan1701** [comment]
Does any body found a fix for this?

**Comment by sanket-t-shah** [comment]
Is there any planned fix for this one?
